name: Node.js CI

on:
  push:
    branches: [ "main" ]

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_CONTENT }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "prepare GCP auth"
      run: echo "$GOOGLE_APPLICATION_CREDENTIALS_CONTENT" > "google-application-credentials.json"
    - run: export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/google-application-credentials.json"
    - run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/google-application-credentials.json" >> $GITHUB_ENV

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - uses: nrwl/nx-set-shas@v4
    - run: npx nx affected -t test build
    - run: npx playwright install --with-deps chromium
    - run: npm install -g firebase-tools
    - run: npx nx affected -t e2e
    - run: npx nx affected -t deploy
    - name: "Remove GCP credentials file"
      if: success() || failure()
      run: rm google-application-credentials.json

